name: Flutter_Timer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^5.0.0
  equatable: ^1.0.0
  wave: ^0.0.0

flutter:
  uses-material-design: true
