name: Flutter_Infinite_List
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^5.0.0
  http: ^0.12.0
  equatable: ^1.0.0
  rxdart: ^0.23.0

  cupertino_icons: ^1.0.0



flutter:
  uses-material-design: true

